# M.R. TechForge — Products Catalog

- id: nfc-starter-pack
  name: Forge NFC Starter Pack
  category: NFC Tags
  badge: Best Value
  status: available
  price: $24.99
  price_note: Includes 6 tags
  image: /assets/img/products/nfc-starter-pack.png
  alt: Forge NFC Starter Pack
  short: "Six pre-labeled NFC tags for daily automation: Wi-Fi, VPN, Home, Car, Guest, SOS."
  features:
    - "6 durable NFC tags (mix of sticker + keychain, configurable)"
    - "Works with Android automations + Forge NFC app"
    - "Simple tap actions (no batteries)"
  cta_label: View Starter Pack
  cta_url: /products/nfc/#nfc-starter-pack

- id: wifi-toggle-tag
  name: Forge Wi-Fi Toggle Tag
  category: NFC Tags
  badge: Popular
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/wifi-toggle-tag.png
  alt: Wi-Fi Toggle NFC tag
  short: "Tap to toggle Wi-Fi on/off (perfect for commuting, battery saving, and quick reconnects)."
  features:
    - "Fast Wi-Fi toggle (Android automation)"
    - "Great for saving battery + quick reconnect"
    - "Place on desk, car mount, or charger"
  cta_label: View Wi-Fi Tag
  cta_url: /products/nfc/#wifi-toggle-tag

- id: nfc-business-card-tag
  category: "NFC Tags"
  name: "Business Card Tag"
  badge: "Pro"
  short: "A tap-to-share NFC business card — your contact info, links, and socials in one clean tap."
  features:
    - "Tap to open your contact card + link hub"
    - "Optional vCard download"
    - "Works great on modern Android; iPhone support varies by use-case"
    - "Custom branding/label available"
  price: "—"
  price_note: ""
  image: "/assets/img/products/nfc-business-card-tag.png"
  alt: "A minimal NFC business card tag on a desk"
  cta_label: "View Details"
  cta_url: "/products/nfc/#nfc-business-card-tag"

- id: vpn-connect-tag
  name: Forge VPN Connect Tag
  category: NFC Tags
  badge: Secure
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/vpn-connect-tag.png
  alt: VPN Connect NFC tag
  short: "Tap to connect your VPN (or open your VPN app) before banking, work, or public Wi-Fi."
  features:
    - "Tap to connect VPN / open VPN app"
    - "Great for public Wi-Fi"
    - "Use with ForgeVPN / WireGuard / your setup"
  cta_label: View VPN Tag
  cta_url: /products/nfc/#vpn-connect-tag

- id: home-mode-tag
  name: Forge Home Mode Tag
  category: NFC Tags
  badge: Smart
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/home-mode-tag.png
  alt: Home Mode NFC tag
  short: "Tap to switch into Home Mode (Wi-Fi on, VPN off, smart home dashboard, comfy settings)."
  features:
    - "Connect home Wi-Fi"
    - "Toggle VPN to your preference"
    - "Open dashboard / app set"
  cta_label: View Home Tag
  cta_url: /products/nfc/#home-mode-tag

- id: car-mode-tag
  name: Forge Car Mode Tag
  category: NFC Tags
  badge: Drive
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/car-mode-tag.png
  alt: Car Mode NFC tag
  short: "Tap for Car Mode (Bluetooth on, maps, music, volume, and drive-ready settings)."
  features:
    - "Bluetooth + navigation shortcut"
    - "Start playlist / podcast"
    - "Optional focus / DND while driving"
  cta_label: View Car Tag
  cta_url: /products/nfc/#car-mode-tag

- id: guest-wifi-tag
  name: Forge Guest Wi-Fi Tag
  category: NFC Tags
  badge: Friendly
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/guest-wifi-tag.png
  alt: Guest Wi-Fi NFC tag
  short: "Tap to share guest Wi-Fi (QR code / link / instructions) — perfect for friends and family."
  features:
    - "Tap to open a Guest Wi-Fi page"
    - "Show QR code or instructions"
    - "Reduces “what’s your Wi-Fi?” texts"
  cta_label: View Guest Tag
  cta_url: /products/nfc/#guest-wifi-tag

- id: sos-emergency-tag
  name: Forge SOS Tag
  category: NFC Tags
  badge: Safety
  status: available
  price: $6.99
  price_note: Single tag
  image: /assets/img/products/sos-emergency-tag.png
  alt: SOS NFC tag
  short: "Tap to trigger an SOS action (text a contact, share location, call a number, open medical info)."
  features:
    - "Emergency shortcut / preset message"
    - "Share location quickly"
    - "Keep on keychain or nightstand"
  cta_label: View SOS Tag
  cta_url: /products/nfc/#sos-emergency-tag

- id: forge-nfc-android-app
  name: Forge NFC Android App
  category: Apps
  badge: Free
  status: available
  price: $0
  price_note: Android
  image: /assets/img/products/forge-nfc-android-app.png
  alt: Forge NFC Android app
  short: "Guided setup for your tags, plus starter automations and tap-to-run shortcuts."
  features:
    - "Guided NFC tag setup"
    - "Starter actions + templates"
    - "Fast, clean UI"
  cta_label: Learn More
  cta_url: /products/nfc/#forge-nfc-android-app

- id: forge-nfc-watch-app
  name: Forge NFC Wear OS Companion
  category: Apps
  badge: Coming Soon
  status: planned
  price: TBD
  price_note: Wear OS
  image: /assets/img/products/forge-nfc-watch-app.png
  alt: Forge NFC Wear OS companion app
  short: "Future companion for quick actions, confirmations, and tag management from your wrist."
  features:
    - "Quick action triggers"
    - "Status / confirmations"
    - "Designed for Wear OS"
  cta_label: Coming Soon
  cta_url: /products/nfc/#forge-nfc-watch-app

# ==========================================================
# FORGE LAB — LEARNING & EXPLORATION
# Hands-on systems • Guided learning • BYO hardware
# ==========================================================

- id: lab-bootable-linux-toolkit
  category: forge-lab
  name: "Bootable Linux Toolkits"
  image: /assets/images/lab/bootable-linux.jpg
  description: >
    Explore live-boot Linux environments used for system recovery,
    diagnostics, and learning. This lab focuses on understanding
    how bootable toolkits work, when to use them, and how to safely
    create your own using trusted distributions.
  focus_areas:
    - Live Linux environments
    - System recovery concepts
    - Safe diagnostics
    - Boot media fundamentals
  notes: "Educational use only • Bring your own USB drive"

- id: lab-sdr-fundamentals
  category: forge-lab
  name: "Software-Defined Radio Fundamentals"
  image: /assets/images/lab/sdr-fundamentals.jpg
  description: >
    A guided introduction to software-defined radio concepts.
    Learn how modern radios use software to receive, visualize,
    and analyze signals — without diving into unsafe or regulated
    transmission scenarios.
  focus_areas:
    - SDR concepts
    - Signal visualization
    - Software tooling
    - Hardware compatibility awareness
  notes: "Receive-only learning focus • Hardware optional"

- id: lab-self-hosted-web
  category: forge-lab
  name: "Self-Hosted Web Fundamentals"
  image: /assets/images/lab/self-hosted-web.jpg
  description: >
    Learn the fundamentals behind hosting a simple website locally.
    This lab explores web servers, networking basics, and security
    considerations — with an emphasis on learning, not production hosting.
  focus_areas:
    - Local web servers
    - Networking basics
    - Security awareness
    - Development workflows
  notes: "Learning & development use • Not public hosting"

- id: lab-linux-exploration
  category: forge-lab
  name: "Linux Exploration & Migration"
  image: /assets/images/lab/linux-exploration.jpg
  description: >
    A practical learning lab for exploring Linux as a daily-use
    operating system. Covers desktop environments, file systems,
    software management, and how Linux differs from Windows or macOS.
  focus_areas:
    - Linux desktop basics
    - System configuration
    - File systems
    - Everyday workflows
  notes: "Bring your own computer • No resale hardware"

- id: lab-raspberry-pi-platform
  category: forge-lab
  name: "Raspberry Pi as a Learning Platform"
  image: /assets/images/lab/raspberry-pi-platform.jpg
  description: >
    Use the Raspberry Pi as a hands-on learning platform to understand
    Linux systems, networking, and small-scale services. Focuses on
    experimentation, clarity, and safe exploration — not production devices.
  focus_areas:
    - Single-board computers
    - Linux fundamentals
    - Local services
    - System experimentation
  notes: "Educational focus • Hardware not provided"

- id: automated-android-app-toolkit
  category: software-toolkits
  name: "Automated Android App Toolkit"
  short_name: "Android Build Toolkit"
  image: /assets/images/products/android-build-toolkit.jpg
  description: >
    A self-contained Docker-based Android build environment designed for CLI-first workflows.
    Clone your repo, run one command, and produce APKs/AABs without installing the Android SDK locally.
    Built for reproducible builds on laptops, Chromebooks, VPS/CI, and headless systems.
  short_features:
    - Docker-based, self-contained environment
    - CLI-first (headless-friendly)
    - Reproducible builds across machines
    - Works great for CI pipelines
  badge: "New"
  cta_label: "Learn More"
  url: /products/software-toolkits/automated-android-app-toolkit/