# M.R. TechForge — Products Catalog

- id: mrtf-nfc-starter-pack
  name: "MRTF NFC Starter Pack"
  category: "NFC Tags"
  badge: "Best Value"
  status: "available"
  price: "$24.99"
  price_note: "Includes 6 tags"
  image: "/assets/img/products/nfc-starter-pack.webp"
  alt: "MRTF NFC Starter Pack"
  short: "Six pre-labeled NFC tags for daily automation: Wi-Fi, VPN, Home, Car, Guest, SOS."
  features:
    - "6 durable NFC tags (mix of sticker + keychain, configurable)"
    - "Works with Android automations + MRTF NFC App"
    - "Simple tap actions (no batteries)"
  compatibility:
    - "Android (NFC-enabled phones)"
    - "Works great with Tasker / routines (optional)"
  includes:
    - "6× NFC tags"
    - "Quick-start setup guide (QR)"
  cta_label: "View Starter Pack"
  cta_url: "/products/#mrtf-nfc-starter-pack"

- id: wifi-toggle-tag
  name: "Wi-Fi Toggle Tag"
  category: "NFC Tags"
  badge: "Popular"
  status: "available"
  price: "$6.99"
  price_note: "Single tag"
  image: "/assets/img/products/wifi-toggle-tag.webp"
  alt: "Wi-Fi Toggle NFC tag"
  short: "Tap to toggle Wi-Fi on/off (perfect for commuting, battery saving, and quick reconnects)."
  features:
    - "Fast Wi-Fi toggle"
    - "Optional: connect to a specific SSID"
    - "Label-ready (clean minimal design)"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View Wi-Fi Tag"
  cta_url: "/products/#wifi-toggle-tag"

- id: vpn-connect-tag
  name: "VPN Connect Tag"
  category: "NFC Tags"
  badge: "MRTF Favorite"
  status: "available"
  price: "$7.99"
  price_note: "Single tag"
  image: "/assets/img/products/vpn-connect-tag.webp"
  alt: "VPN Connect NFC tag"
  short: "Tap to connect/disconnect your VPN profile for instant secure browsing."
  features:
    - "One-tap VPN connect/disconnect"
    - "Designed for ForgeVPN / home VPN workflows"
    - "Great for public Wi-Fi"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View VPN Tag"
  cta_url: "/products/#vpn-connect-tag"

- id: home-mode-tag
  name: "Home Mode Tag"
  category: "NFC Tags"
  status: "available"
  price: "$7.99"
  price_note: "Single tag"
  image: "/assets/img/products/home-mode-tag.webp"
  alt: "Home Mode NFC tag"
  short: "Tap to switch into Home Mode: volume, brightness, Wi-Fi, and your preferred settings."
  features:
    - "Home profile toggle"
    - "Quiet hours / ringtone presets"
    - "Optional smart-home hooks (future)"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View Home Mode"
  cta_url: "/products/#home-mode-tag"

- id: car-mode-tag
  name: "Car Mode Tag"
  category: "NFC Tags"
  status: "available"
  price: "$7.99"
  price_note: "Single tag"
  image: "/assets/img/products/car-mode-tag.webp"
  alt: "Car Mode NFC tag"
  short: "Tap to launch navigation + set driving-friendly audio and screen settings."
  features:
    - "Launch Maps + music/podcast"
    - "Hands-free friendly defaults"
    - "Optional: Bluetooth device targeting"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View Car Mode"
  cta_url: "/products/#car-mode-tag"

- id: guest-wifi-tag
  name: "Guest Wi-Fi Tag"
  category: "NFC Tags"
  badge: "Party Trick"
  status: "available"
  price: "$8.99"
  price_note: "Single tag"
  image: "/assets/img/products/guest-wifi-tag.webp"
  alt: "Guest Wi-Fi NFC tag"
  short: "Tap to join your guest network without reading passwords out loud."
  features:
    - "One-tap Wi-Fi join"
    - "Great for visitors + smart devices"
    - "Keeps your main network separate"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View Guest Wi-Fi"
  cta_url: "/products/#guest-wifi-tag"

- id: sos-emergency-tag
  name: "SOS Emergency Tag"
  category: "NFC Tags"
  badge: "Safety"
  status: "available"
  price: "$9.99"
  price_note: "Single tag"
  image: "/assets/img/products/sos-emergency-tag.webp"
  alt: "SOS Emergency NFC tag"
  short: "Tap to run your emergency workflow (call/text, location share, or preset alert actions)."
  features:
    - "Emergency shortcut trigger"
    - "Location-sharing workflow support"
    - "Customizable for your needs"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "1× NFC tag"
    - "Setup QR"
  cta_label: "View SOS Tag"
  cta_url: "/products/#sos-emergency-tag"

- id: mrtf-nfc-android-app
  name: "MRTF NFC Android App"
  category: "Apps"
  badge: "Companion"
  status: "available"
  price: "Free"
  price_note: "Core features"
  image: "/assets/img/products/mrtf-nfc-android-app.webp"
  alt: "MRTF NFC Android App"
  short: "The companion app that programs tags and runs Forge-style tap automations."
  features:
    - "Guided tag setup"
    - "Profiles: Home / Car / Work"
    - "Works alongside Tasker (optional)"
  compatibility:
    - "Android (NFC-enabled phones)"
  includes:
    - "App install + onboarding"
  cta_label: "Get the App"
  cta_url: "/mrtf-nfc-app/"

- id: mrtf-nfc-watch-app
  name: "MRTF NFC Watch Companion"
  category: "Apps"
  badge: "Coming Soon"
  status: "coming_soon"
  price: "Planned"
  price_note: "Wear OS"
  image: "/assets/img/products/mrtf-nfc-watch-app.webp"
  alt: "MRTF NFC Watch Companion for Wear OS"
  short: "A future Wear OS companion for quick actions, status, and tag-triggered workflows."
  features:
    - "Quick toggles + shortcuts"
    - "Status tiles + complication ideas"
    - "Fast “tap → confirm → run” flows"
  compatibility:
    - "Wear OS (future)"
  includes:
    - "Early-access roadmap updates (when available)"
  cta_label: "Roadmap"
  cta_url: "/products/#mrtf-nfc-watch-app"