# ======================================================
# M.R. TechForge — Product & Service Catalog
# Used by /products/ and product category pages
# ======================================================

# -------------------------
# PRIVATE CLOUD / VPN
# -------------------------

- name: MRTF Private Cloud Node
  description: >
    A managed, on-prem private cloud and VPN entrypoint for your small business.
    Your data lives on a secure mini-server inside your office, with encrypted
    remote access and nightly backups to a separate, Windows-readable drive.
  price: 0
  image: /assets/images/private_cloud_node.png
  category: private-cloud
  short_features:
    - "Your data stays on hardware you own, inside your building"
    - "Secure WireGuard-based VPN access"
    - "Nightly backups to USB or a network target"
    - "Fully managed by M.R. TechForge (MRTF)"


# -------------------------
# NFC TAGS & AUTOMATIONS
# -------------------------

- name: Wi-Fi Toggle NFC Tag
  description: Tap to instantly enable or disable Wi-Fi on your device.
  price: 6
  image: /assets/images/nfc_wifi_tag.png
  category: nfc

- name: VPN Connect NFC Tag
  description: Tap to connect your device to your private WireGuard VPN.
  price: 8
  image: /assets/images/nfc_vpn_tag.png
  category: nfc

- name: Home Mode NFC Tag
  description: >
    Tap to instantly enable or disable your home connectivity — toggling Wi-Fi,
    Bluetooth, and optional Do Not Disturb in one go. Works with Android and iPhone.
  price: 7
  image: /assets/images/nfc_home_mode_tag.png
  category: nfc
  short_features:
    - "Toggle Wi-Fi + Bluetooth together"
    - "Optional Do Not Disturb"
    - "Android native toggle / iPhone Shortcuts"
    - "Perfect for desks or entryways"

- name: Guest Wi-Fi NFC Tag
  description: >
    Instantly share guest Wi-Fi. Android auto-connects; iPhone opens a QR code.
    Ideal for homes, offices, or AirBnB setups.
  price: 6
  image: /assets/images/nfc_guest_wifi_tag.png
  category: nfc
  short_features:
    - "One-tap Wi-Fi access"
    - "Android auto-connect / iPhone QR fallback"
    - "Securely stores your SSID + password"
    - "Includes setup card"

- name: SOS Emergency NFC Tag
  description: >
    A single tap sends or prepares your emergency text — optionally with GPS
    location. Keep one on a keychain or bedside.
  price: 8
  image: /assets/images/nfc_sos_tag.png
  category: nfc
  short_features:
    - "Tap to trigger emergency text"
    - "Optional GPS link"
    - "Android: direct SMS intent / iPhone: Shortcut"
    - "Bright red emergency design"

- name: Car Mode NFC Tag
  description: >
    Launch navigation, toggle Bluetooth, and enable Do Not Disturb as soon as
    you enter your car. Fully configurable.
  price: 7
  image: /assets/images/nfc_car_mode_tag.png
  category: nfc
  short_features:
    - "Launch maps or playlists"
    - "Turns on Bluetooth + DND"
    - "Android Tasker / iPhone Shortcuts"
    - "Mount near dash"

- name: NFC Business Card
  description: >
    A reusable, tap-to-share digital business card. Send contact info instantly
    without printing new cards.
  price: 9
  image: /assets/images/nfc_business_card.png
  category: nfc
  short_features:
    - "Stores full vCard or URL"
    - "Android & iPhone compatible"
    - "Reusable — rewrite anytime"
    - "Optional custom design"

- name: Serenity (Bedtime) NFC Tag
  description: >
    A tap transitions your device into nighttime mode: Sleep, DND, or quiet time.
    Ideal for nightstands.
  price: 6
  image: /assets/images/nfc_serenity_tag.png
  category: nfc
  short_features:
    - "Enables Sleep / DND mode"
    - "Android: NFC Tools or Tasker"
    - "iPhone: Sleep Focus"
    - "Optional ‘Wake’ companion tag"

- name: Car Finder NFC Tag
  description: >
    Tap before walking away to drop a pin and save your parking location.
    Works on Android and iPhone.
  price: 7
  image: /assets/images/nfc_car_finder_tag.png
  category: nfc
  short_features:
    - "Tap to mark parking spot"
    - "Opens Google/Apple Maps"
    - "Android geo: link / iPhone Shortcut"
    - "Durable adhesive tag"


# -------------------------
# TECH GADGETS & HARDWARE
# -------------------------

- name: ForgeSecure USB
  description: Pre-loaded USB with privacy and digital security tools.
  price: 12
  image: /assets/images/forge_usb.png
  category: gadgets

- name: MRTF Ultimate Drive
  description: >
    A pre-loaded multi-boot USB toolkit for diagnostics, repair, forensics,
    cloning, and recovery. Built on Ventoy.
  price: 40
  image: /assets/images/mrtf_ultimate_drive_generic.png
  category: gadgets
  short_features:
    - "Multi-boot Linux & recovery tools"
    - "Kali for advanced troubleshooting"
    - "Rescue & anti-virus utilities"
    - "Disk cloning & hardware diagnostics"
    - "Easy Ventoy drag-and-drop updates"


# -------------------------
# VIRTUAL SERVICES
# -------------------------

- name: Remote Support Session
  description: One-hour secure remote support for troubleshooting or personalized guidance.
  price: 45
  image: /assets/images/remote_support.png
  category: virtual